from django.urls import path, include
from rest_framework.documentation import include_docs_urls
from rest_framework import routers 
from . import views

# Create a router object to automatically handle URL routing for the API
router = routers.DefaultRouter()

# Register the TaskViewSet with the router, associating it with the 'tasks' endpoint
router.register(r'tasks', views.TaskViewSet, 'tasks')

# Define the URL patterns for the API, including the routes generated by the router
urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('docs/', include_docs_urls(title="Task API", description="A simple API for managing tasks")),
]

# This code creates the necessary routes for the Task API,
# automatically generating the endpoints for GET, POST, PUT, and DELETE operations.